openapi: 3.0.1
info:
  title: API
  # description: ''
  # termsOfService: http://swagger.io/terms/
  contact:
    email: phphe@outlook.com
  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
# externalDocs:
#   description: Find out more about Swagger
#   url: http://swagger.io
servers:
- url: https://aaprint.co/api
- url: http://localhost:8072/api
tags:
- name: base
- name: file
- name: user
- name: order
- name: shop
paths: {}
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: app.plugins.jwt_auth.decode_token
